name: lodestar-engagement-status
development: true

imageName: "lodestar-engagement-status"
imageTag: "latest"

builderImage: registry.access.redhat.com/ubi8/openjdk-11
builderImageTag: 1.3

servicePort: 8080

git:
  uri: https://github.com/rht-labs/lodestar-engagement-status.git
  ref: main

api:
  gitlab: http://gitlab.com
  engagement: http://lodestar-git-api:8080

tokens:
  webhook: nope
  gitlab: nope
